### PR TITLE
Added build systems for Games(Pyinstaller and Buildozer)

### PR DESCRIPTION
**Pull request by T-Dynamos**
Do not merge now

### CODE REVIEW

**Comment by pyGuru123** [comment]
I'm still working on snake

**Comment by T-Dynamos** [comment]
> I'm still working on snake

I will also be adding build systems for windows using pyinstaller soon(for all games)

**Comment by T-Dynamos** [comment]
Main issue is that pygame is unable to open files 
Reference: https://stackoverflow.com/questions/57766969/cannot-open-image-in-pygame-on-android
Error:
```
2022-05-15 11:43:55.046 30574 30987 com.pyguru.connected I python : pygame.error: Unable to open file '/data/data/com.pyguru.connected/files/app/Sounds/flip.mp3'
```

**Comment by pyGuru123** [comment]
I already told you, pygame wont work as apk. so should i close this PR ?

**Comment by T-Dynamos** [comment]
Wait till night

**Comment by T-Dynamos** [comment]
Soi just proved pygame works on android
IMG_20220515_173109

Code used https://github.com/T-Dynamos/Python-Games/blob/master/Connected/main.py
```
import pygame, sys
from pygame.locals import *

#Set up pygame
pygame.init()

#Set up the window
windowSurface = pygame.display.set_mode((500, 400), 0 , 32)
pygame.display.set_caption('Hello World')

#Set up the colors
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
WHITE = (255,255,255)

#Set up fonts
basicFont = pygame.font.SysFont(None, 60)

#Set up the text
text = basicFont.render('HELLO WORLD', True, (0,0,0))
textRect = text.get_rect()
textRect.centerx = windowSurface.get_rect().centerx
textRect.centery = windowSurface.get_rect().centery

#Draw the white background onto the surface
windowSurface.fill(WHITE)


#Get a pixel array of the surface
pixArray = pygame.PixelArray(windowSurface)
pixArray[480][380] = BLACK
del pixArray

#Draw the text onto the surface
windowSurface.blit(text,textRect)

#Draw the window onto the screen
pygame.display.update()

#Run the game loop
while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
```
Test apk now in actions https://github.com/T-Dynamos/Python-Games/actions/runs/2327084678 (Download package-connected.zip)

**Comment by T-Dynamos** [comment]
I am on it

**Pull request closed without merging**
